from pathlib import Path

ROOT = Path(__file__).resolve().parent / "sample-documents"


def pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def build_pdf(pages: list[list[str]]) -> bytes:
    objects: list[str | None] = []
    objects.append("<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(None)
    objects.append("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    page_numbers: list[int] = []

    for index, lines in enumerate(pages):
        page_number = 4 + index * 2
        content_number = 5 + index * 2
        page_numbers.append(page_number)

        stream_lines = ["BT", "/F1 12 Tf", "14 TL", "50 760 Td"]
        for line_index, line in enumerate(lines):
            if line_index > 0:
                stream_lines.append("T*")
            stream_lines.append(f"({pdf_escape(line)}) Tj")
        stream_lines.append("ET")
        stream = "\n".join(stream_lines) + "\n"

        objects.append(
            "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            f"/Resources << /Font << /F1 3 0 R >> >> /Contents {content_number} 0 R >>"
        )
        objects.append(f"<< /Length {len(stream.encode('utf-8'))} >>\nstream\n{stream}endstream")

    kids = " ".join(f"{number} 0 R" for number in page_numbers)
    objects[1] = f"<< /Type /Pages /Kids [{kids}] /Count {len(page_numbers)} >>"

    pdf_text = "%PDF-1.4\n"
    offsets = [0]
    for object_number, obj in enumerate(objects, start=1):
        offsets.append(len(pdf_text.encode("utf-8")))
        pdf_text += f"{object_number} 0 obj\n{obj}\nendobj\n"

    startxref = len(pdf_text.encode("utf-8"))
    pdf_text += f"xref\n0 {len(objects) + 1}\n"
    pdf_text += "0000000000 65535 f \n"
    for offset in offsets[1:]:
        pdf_text += f"{offset:010d} 00000 n \n"
    pdf_text += f"trailer\n<< /Root 1 0 R /Size {len(objects) + 1} >>\n"
    pdf_text += f"startxref\n{startxref}\n%%EOF\n"
    return pdf_text.encode("utf-8")


PDF_SPECS: dict[Path, list[list[str]]] = {
    ROOT / "small-pdf" / "rag-onboarding-guide.pdf": [
        [
            "Enterprise RAG Onboarding Guide",
            "Supported uploads: PDF and TXT.",
            "Files are stored before processing begins.",
            "Parsing extracts text page by page.",
            "Chunking uses a 512 character target with 50 character overlap.",
            "Page numbers are preserved for citations.",
        ],
        [
            "Embeddings use BAAI/bge-m3.",
            "Query embeddings must use the same BAAI/bge-m3 model.",
            "Query text may use the retrieval prefix for BGE.",
            "Vector search uses Pinecone with top_k 50.",
            "Reranking uses BAAI/bge-reranker-v2-m3 with top_k 5.",
        ],
    ],
    ROOT / "small-pdf" / "compliance-faq.pdf": [
        [
            "Compliance FAQ",
            "Audit logs are retained for 365 days.",
            "Secrets must remain in environment variables.",
            "Secrets must never be committed to the repository.",
            "Production data access requires platform owner approval.",
        ],
        [
            "Lost badges must be reported within 1 hour.",
            "Receipts must be submitted within 30 days.",
            "Compliance answers should cite the policy source.",
        ],
    ],
    ROOT / "medium-pdf" / "architecture-overview.pdf": [
        [
            "Architecture Overview",
            "Frontend uses Next.js 14 for the user interface.",
            "Backend uses FastAPI for APIs and orchestration.",
            "PostgreSQL stores documents, chunks, and chat history.",
            "Redis supports caching and background jobs.",
        ],
        [
            "Pinecone is the vector database.",
            "Embeddings use BAAI/bge-m3 with 1024 dimensions.",
            "Queries must use the same BAAI/bge-m3 embedding model.",
            "Retrieved candidates are reranked with BAAI/bge-reranker-v2-m3.",
        ],
        [
            "Answers are generated by Meta-Llama-3.1-8B-Instruct via vLLM.",
            "Streaming responses are sent with Server-Sent Events.",
            "Retrieval defaults use top_k 50 and rerank_top_k 5.",
        ],
    ],
    ROOT / "edge-cases" / "sparse-text.pdf": [["Sparse Text Fixture", "Approved.", "2026."]],
}


if __name__ == "__main__":
    for path, pages in PDF_SPECS.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(build_pdf(pages))
        print(f"created {path}")

